"use client";

import { useEffect, useState } from "react";
import { BookOpen, Bot, CalendarDays, ChevronRight, Church, Clock3, CloudSun, FolderKanban, Home, Menu, Music2, Plus, Sparkles, Trophy, Users, X, Zap } from "lucide-react";
import { Area, courses, familyEvents, fallbackGame, projects } from "@/lib/data";

const nav: { label: Area; icon: typeof Home }[] = [
  { label: "Home", icon: Home }, { label: "School", icon: BookOpen }, { label: "Projects", icon: FolderKanban },
  { label: "Family", icon: Users }, { label: "Faith", icon: Church }, { label: "Fun", icon: Music2 }, { label: "Sports", icon: Trophy }
];

export function CommandCenter() {
  const [area, setArea] = useState<Area>("Home");
  const [selected, setSelected] = useState<string>();
  const [assistant, setAssistant] = useState(false);
  const [ambient, setAmbient] = useState(false);
  const [menu, setMenu] = useState(false);
  const [now, setNow] = useState(new Date());

  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 30_000); return () => clearInterval(timer); }, []);

  const go = (next: Area) => { setArea(next); setSelected(undefined); setMenu(false); };
  if (ambient) return <AmbientMode onExit={() => setAmbient(false)} />;

  return (
    <div className="min-h-screen lg:grid lg:grid-cols-[242px_1fr]">
      <aside className={`fixed inset-y-0 left-0 z-40 flex w-[270px] flex-col bg-navy px-5 py-7 text-white transition-transform lg:sticky lg:top-0 lg:h-screen lg:w-auto ${menu ? "translate-x-0" : "-translate-x-full lg:translate-x-0"}`}>
        <button aria-label="Close menu" className="absolute right-4 top-4 rounded-xl p-2 lg:hidden" onClick={() => setMenu(false)}><X /></button>
        <div className="mb-10 flex items-center gap-3 px-2">
          <div className="grid h-11 w-11 place-items-center rounded-2xl bg-gator"><Zap size={23} fill="currentColor" /></div>
          <div><p className="display text-[17px] font-extrabold leading-none">SUPER BRAIN</p><p className="mt-1 text-[10px] font-bold tracking-[.18em] text-white/45">DR. DISRUPTOR</p></div>
        </div>
        <nav aria-label="Primary" className="space-y-1.5">
          {nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => go(label)} className={`flex min-h-12 w-full items-center gap-3 rounded-xl px-4 text-left text-sm font-semibold transition ${area === label ? "bg-white text-navy shadow-lg" : "text-white/65 hover:bg-white/10 hover:text-white"}`}><Icon size={19} strokeWidth={area === label ? 2.5 : 2} />{label}</button>)}
        </nav>
        <div className="mt-auto rounded-2xl border border-white/10 bg-white/[.06] p-4">
          <div className="mb-3 flex items-center gap-2 text-xs font-bold text-white/75"><CloudSun size={18} className="text-orange-300" /> GAINESVILLE · 86°</div>
          <button onClick={() => setAmbient(true)} className="w-full rounded-xl border border-white/15 py-2.5 text-xs font-bold text-white/70 hover:bg-white/10">Enter ambient mode</button>
        </div>
      </aside>

      <main className="min-w-0 bg-[#f4f3ee]">
        <header className="flex h-[78px] items-center justify-between border-b border-ink/[.07] bg-[#f4f3ee]/90 px-5 backdrop-blur md:px-9 lg:px-12">
          <div className="flex items-center gap-3"><button onClick={() => setMenu(true)} className="rounded-xl bg-white p-2.5 shadow-sm lg:hidden"><Menu size={21} /></button><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/40">Your command center</p><h1 className="display text-lg font-extrabold">{area === "Home" ? "Good morning, Eric." : area}</h1></div></div>
          <div className="hidden items-center gap-5 md:flex"><div className="text-right"><p className="text-sm font-bold">{now.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</p><p className="text-[11px] font-medium text-ink/45">{now.toLocaleDateString([], { weekday: "long", month: "short", day: "numeric" })}</p></div><div className="grid h-10 w-10 place-items-center rounded-full bg-[#dbe5ec] text-sm font-extrabold text-blue">ED</div></div>
        </header>
        <div className="mx-auto max-w-[1440px] p-5 pb-28 md:p-9 lg:p-12">
          {area === "Home" ? <HomeView go={go} /> : <AreaView area={area} selected={selected} onSelect={setSelected} />}
        </div>
      </main>
      <button onClick={() => setAssistant(true)} className="fixed bottom-5 right-5 z-30 flex min-h-14 items-center gap-2 rounded-2xl bg-gator px-5 font-bold text-white shadow-[0_12px_30px_rgba(232,92,43,.35)] transition hover:-translate-y-0.5 md:bottom-8 md:right-8"><Sparkles size={20} /> Ask Brain</button>
      {assistant && <Assistant area={area} selected={selected} close={() => setAssistant(false)} />}
      {menu && <button aria-label="Close navigation overlay" onClick={() => setMenu(false)} className="fixed inset-0 z-30 bg-ink/35 lg:hidden" />}
    </div>
  );
}

function HomeView({ go }: { go: (area: Area) => void }) {
  return <div className="fade-in space-y-6">
    <section className="relative overflow-hidden rounded-[28px] bg-navy p-7 text-white shadow-card md:p-9">
      <div className="absolute inset-y-0 right-0 w-1/2 subtle-grid opacity-20" /><div className="relative max-w-xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-orange-200"><Sparkles size={13}/> Wednesday focus</div><h2 className="display text-3xl font-extrabold leading-tight md:text-[40px]">Make the important<br className="hidden sm:block"/> things feel possible.</h2><p className="mt-3 text-sm leading-6 text-white/55">You have 3 priority actions today. Start with the school item—it has the nearest deadline.</p></div>
    </section>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <div className="space-y-6">
        <section className="card rounded-3xl p-6"><SectionTitle icon={Zap} title="Today’s priorities" note="3 actions" />
          <div className="mt-5 divide-y divide-ink/[.07]">{[
            ["01", "Complete FYC 6234 literature synthesis", "School · Due 4:00 PM", "bg-orange-50 text-gator"],
            ["02", "Review Super Brain dashboard prototype", "Projects · 45 min", "bg-blue-50 text-blue"],
            ["03", "Confirm Crystal’s appointment details", "Family · Before 3:00 PM", "bg-purple-50 text-purple-600"]
          ].map((p) => <button key={p[0]} className="group flex min-h-[78px] w-full items-center gap-4 py-3 text-left"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-xs font-extrabold ${p[3]}`}>{p[0]}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{p[1]}</span><span className="mt-1 block text-xs text-ink/45">{p[2]}</span></span><ChevronRight size={18} className="text-ink/20 transition group-hover:translate-x-1" /></button>)}</div>
        </section>
        <section className="card rounded-3xl p-6"><SectionTitle icon={BookOpen} title="School urgency" note="1 due today" action={() => go("School")} />
          <div className="mt-5 grid gap-3 md:grid-cols-3">{courses.slice(0,3).map((c, i) => <button onClick={() => go("School")} key={c.code} className="rounded-2xl border border-ink/[.07] p-4 text-left transition hover:border-gator/30 hover:bg-orange-50/40"><span className={`text-[10px] font-extrabold uppercase tracking-widest ${i===0 ? "text-gator" : "text-blue"}`}>{c.code}</span><span className="mt-2 block text-sm font-bold leading-5">{c.due}</span><span className="mt-2 flex items-center gap-1 text-[11px] text-ink/45"><Clock3 size={12}/>{c.when}</span></button>)}</div>
        </section>
      </div>
      <div className="space-y-6">
        <section className="card rounded-3xl p-6"><SectionTitle icon={CalendarDays} title="Family today" note="3 events" action={() => go("Family")} /><div className="mt-5 space-y-4">{familyEvents.map(e => <div key={e.time+e.title} className="flex gap-4"><div className="w-10 text-right"><p className="text-sm font-extrabold">{e.time}</p><p className="text-[9px] font-bold text-ink/35">{e.period}</p></div><div className={`w-1 rounded-full ${e.tone === "orange" ? "bg-gator" : e.tone === "blue" ? "bg-blue" : "bg-purple-400"}`} /><p className="py-1 text-sm font-semibold">{e.title}</p></div>)}</div></section>
        <GameCard go={() => go("Sports")} />
        <section className="card rounded-3xl p-6"><SectionTitle icon={FolderKanban} title="Project pulse" note="3 active" action={() => go("Projects")} /><div className="mt-5 space-y-4">{projects.slice(0,2).map(p => <div key={p.name}><div className="flex justify-between text-xs"><span className="font-bold">{p.name}</span><span className="font-extrabold" style={{color:p.color}}>{p.stage}</span></div><p className="mt-1 text-[11px] text-ink/45">Next: {p.next}</p></div>)}</div></section>
      </div>
    </div>
  </div>;
}

function SectionTitle({ icon: Icon, title, note, action }: { icon: typeof Home; title: string; note: string; action?: () => void }) { return <div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><Icon size={18} className="text-gator"/><h3 className="display text-lg font-extrabold">{title}</h3></div><button onClick={action} className="text-[10px] font-bold uppercase tracking-widest text-ink/35 hover:text-gator">{note} {action && "→"}</button></div> }

function GameCard({ go }: { go: () => void }) { return <button onClick={go} className="w-full overflow-hidden rounded-3xl bg-[#173d72] text-left text-white shadow-card"><div className="flex items-center justify-between border-b border-white/10 px-6 py-4"><span className="text-[10px] font-bold uppercase tracking-[.18em] text-white/55">Next Gators game</span><span className="rounded-full bg-gator px-2.5 py-1 text-[9px] font-extrabold">17 DAYS</span></div><div className="p-6"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-full border-2 border-orange-400 bg-blue text-2xl font-black italic">F</div><div><p className="text-xs font-semibold text-white/50">FLORIDA vs.</p><p className="display text-xl font-extrabold">{fallbackGame.opponent}</p></div></div><div className="mt-5 flex justify-between text-xs"><span>{fallbackGame.date}</span><span className="font-bold text-orange-300">{fallbackGame.kickoff}</span></div></div></button> }

function AreaView({ area, selected, onSelect }: { area: Area; selected?: string; onSelect: (v: string) => void }) {
  if (area === "School") return <GenericHeader eyebrow="Academic command" title="School urgency" intro="One clear view of every deadline, across every program."><div className="mb-6 flex gap-2 overflow-x-auto pb-2">{["Do Now", "This Week", "Upcoming", "Deep Work", "Completed"].map((x,i)=><button key={x} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-bold ${i===0?"bg-navy text-white":"bg-white text-ink/50"}`}>{x}</button>)}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map(c=><button key={c.code} onClick={()=>onSelect(c.code)} className={`card rounded-3xl p-5 text-left transition hover:-translate-y-1 ${selected===c.code?"ring-2 ring-gator":""}`}><p className="text-[10px] font-bold uppercase tracking-widest text-blue">{c.school}</p><h3 className="mt-2 display text-lg font-extrabold">{c.code}</h3><p className="text-xs text-ink/45">{c.title}</p><div className="my-5 h-1.5 rounded-full bg-ink/5"><div className="h-full rounded-full bg-gator" style={{width:`${c.progress}%`}}/></div><p className="text-sm font-bold">{c.due}</p><p className="mt-1 text-xs text-ink/40">{c.when} · <span className="text-blue">Synced</span></p></button>)}</div></GenericHeader>;
  if (area === "Projects") return <GenericHeader eyebrow="Relational workspace" title="Project Brain" intro="Everything you’re building, and how the pieces connect."><div className="grid gap-4 lg:grid-cols-3">{projects.map((p,i)=><button key={p.name} onClick={()=>onSelect(p.name)} className="card rounded-3xl p-6 text-left"><div className="mb-6 flex items-center justify-between"><span className="rounded-full px-3 py-1 text-[10px] font-extrabold text-white" style={{background:p.color}}>{p.stage}</span><span className="text-xs text-ink/35">0{i+3} links</span></div><h3 className="display text-xl font-extrabold">{p.name}</h3><p className="mt-1 text-xs text-ink/45">{p.org}</p><div className="mt-6 border-t border-ink/[.07] pt-4"><p className="text-[9px] font-bold uppercase tracking-widest text-ink/35">Next action</p><p className="mt-1 text-sm font-semibold">{p.next}</p></div></button>)}</div><div className="card mt-6 rounded-3xl p-6"><SectionTitle icon={Sparkles} title="Relationship map" note="Live view"/><div className="subtle-grid mt-5 flex min-h-48 items-center justify-around rounded-2xl bg-[#f8f8f5] p-4">{projects.map((p,i)=><div key={p.name} className={`grid h-24 w-24 place-items-center rounded-full border-4 bg-white p-3 text-center text-[10px] font-extrabold shadow-lg ${i===1?"translate-y-8":""}`} style={{borderColor:p.color}}>{p.name}</div>)}</div></div></GenericHeader>;
  if (area === "Family") return <GenericHeader eyebrow="Together this week" title="Family rhythm" intro="The shared schedule, without the scheduling noise."><Week /><div className="mt-6 grid gap-6 md:grid-cols-2"><TaskList name="Eric" tasks={["Confirm Wednesday appointment", "Order school supplies"]}/><TaskList name="Stavros" tasks={["Pack Greek school bag", "Reading — 20 minutes"]}/></div></GenericHeader>;
  const content = area === "Faith" ? ["Church events", "Sunday School", "Gratitude", "Reflection", "Service", "Prayer notes"] : area === "Fun" ? ["Florida Gators", "Family activities", "Movies", "Music", "Restaurants", "Trips", "Weekend ideas"] : ["2026 Schedule", "Next game", "Countdown", "Scores", "Record", "Latest status"];
  return <GenericHeader eyebrow={area === "Faith" ? "Be still" : area === "Fun" ? "Make room for joy" : "Florida Gators football"} title={area} intro={area === "Faith" ? "A calm place for gratitude, reflection, and service." : area === "Fun" ? "Ideas worth looking forward to." : "Schedule, scores, and what’s next—all in one place."}>{area === "Sports" && <div className="mb-6 max-w-sm"><GameCard go={()=>{}}/></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{content.map((x,i)=><button key={x} className="card flex min-h-32 items-start justify-between rounded-3xl p-6 text-left"><div><div className={`mb-5 grid h-9 w-9 place-items-center rounded-xl ${area==="Faith"?"bg-amber-50 text-amber-600":area==="Sports"?"bg-blue-50 text-blue":"bg-purple-50 text-purple-600"}`}>{area==="Faith"?<Church size={18}/>:area==="Sports"?<Trophy size={18}/>:<Music2 size={18}/>}</div><h3 className="font-bold">{x}</h3><p className="mt-1 text-xs text-ink/40">{i===0?"Updated today":"Ready when you are"}</p></div><ChevronRight size={17} className="text-ink/20"/></button>)}</div></GenericHeader>;
}

function GenericHeader({ eyebrow, title, intro, children }: { eyebrow:string; title:string; intro:string; children:React.ReactNode }) { return <div className="fade-in"><div className="mb-8"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-gator">{eyebrow}</p><h2 className="display mt-2 text-3xl font-extrabold md:text-4xl">{title}</h2><p className="mt-2 max-w-xl text-sm text-ink/50">{intro}</p></div>{children}</div> }
function TaskList({name,tasks}:{name:string;tasks:string[]}) { return <div className="card rounded-3xl p-6"><div className="flex justify-between"><h3 className="display text-lg font-extrabold">{name}’s tasks</h3><button aria-label={`Add ${name} task`} className="rounded-lg bg-ink/5 p-1.5"><Plus size={16}/></button></div><div className="mt-5 space-y-3">{tasks.map(t=><label key={t} className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" className="h-5 w-5 accent-orange-600"/>{t}</label>)}</div></div> }
function Week() { const days=["MON 7","TUE 8","WED 9","THU 10","FRI 11","SAT 12","SUN 13"]; return <div className="card overflow-x-auto rounded-3xl p-5"><div className="grid min-w-[750px] grid-cols-7 gap-2">{days.map((d,i)=><div key={d} className={`min-h-56 rounded-2xl p-3 ${i===2?"bg-orange-50 ring-1 ring-orange-200":"bg-[#f8f8f5]"}`}><p className="text-[10px] font-extrabold tracking-wider text-ink/40">{d}</p>{i<5&&<><p className="mt-5 rounded-lg bg-blue/10 p-2 text-[10px] font-bold text-blue">9:00 · Bus</p><p className="mt-2 rounded-lg bg-gator/10 p-2 text-[10px] font-bold text-gator">4:00 · Home</p></>}{i===1&&<p className="mt-2 rounded-lg bg-purple-100 p-2 text-[10px] font-bold text-purple-700">5:00 · Greek</p>}{i===6&&<p className="mt-5 rounded-lg bg-amber-100 p-2 text-[10px] font-bold text-amber-700">10:00 · Sunday School</p>}</div>)}</div></div> }

function Assistant({ area, selected, close }: { area: Area; selected?: string; close:()=>void }) { const [text,setText]=useState(""); const [messages,setMessages]=useState<string[]>([]); const [busy,setBusy]=useState(false); const ask=async()=>{if(!text.trim()||busy)return; const question=text; setText(""); setMessages(m=>[...m,question]); setBusy(true); try { const response=await fetch("/api/brain",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:question,current_screen:area.toLowerCase(),selected_item:selected})}); const data=await response.json() as {answer?:string;error?:string}; setMessages(m=>[...m,data.answer??data.error??"Brain is unavailable right now."]); } catch { setMessages(m=>[...m,"Brain is unavailable right now. Your context is safe—please try again shortly."]); } finally { setBusy(false); }}; return <div className="fixed inset-0 z-50 flex items-end justify-end bg-ink/25 p-0 backdrop-blur-sm md:p-6"><section role="dialog" aria-modal="true" aria-label="Ask Brain assistant" className="flex h-[82vh] w-full flex-col rounded-t-[30px] bg-white shadow-2xl md:h-[650px] md:max-w-md md:rounded-[30px]"><header className="flex items-center justify-between border-b p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gator text-white"><Bot/></div><div><h2 className="display font-extrabold">Ask Brain</h2><p className="text-[10px] text-ink/40">Context: {area}{selected?` · ${selected}`:""}</p></div></div><button onClick={close} className="rounded-xl bg-ink/5 p-2"><X size={20}/></button></header><div className="flex-1 space-y-3 overflow-y-auto p-5"><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-ink/5 p-4 text-sm leading-6">I’m with you. What would make this moment easier?</div>{messages.map((m,i)=><div key={i} className={`max-w-[88%] rounded-2xl p-4 text-sm leading-6 ${i%2===0?"ml-auto rounded-tr-sm bg-navy text-white":"rounded-tl-sm bg-orange-50"}`}>{m}</div>)}{busy&&<div className="text-xs font-bold text-ink/35">Brain is thinking…</div>}</div><div className="border-t p-4"><div className="flex gap-2 rounded-2xl bg-ink/5 p-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void ask()} aria-label="Ask Brain a question" placeholder="What should I do next?" className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none"/><button disabled={busy} onClick={()=>void ask()} className="rounded-xl bg-gator px-4 py-3 text-xs font-bold text-white disabled:opacity-50">Ask</button></div><p className="mt-2 text-center text-[9px] text-ink/30">Text now · Voice and avatar ready architecture</p></div></section></div> }

function AmbientMode({onExit}:{onExit:()=>void}) { return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-navy p-8 text-white"><div className="absolute inset-0 subtle-grid opacity-10"/><button onClick={onExit} className="absolute right-6 top-6 rounded-xl bg-white/10 px-4 py-2 text-xs font-bold">Exit ambient</button><div className="relative w-full max-w-5xl text-center"><p className="text-sm font-bold uppercase tracking-[.3em] text-orange-300">Wednesday · Today</p><p className="display mt-7 text-6xl font-extrabold md:text-8xl">Make space<br/>for what matters.</p><div className="mx-auto mt-12 grid max-w-3xl gap-4 text-left md:grid-cols-3"><div className="rounded-2xl bg-white/10 p-5"><BookOpen className="text-orange-300"/><p className="mt-5 text-xs text-white/45">SCHOOL</p><p className="mt-1 font-bold">1 item due today</p></div><div className="rounded-2xl bg-white/10 p-5"><Users className="text-blue-300"/><p className="mt-5 text-xs text-white/45">FAMILY</p><p className="mt-1 font-bold">Next: Home · 4:00</p></div><div className="rounded-2xl bg-white/10 p-5"><Trophy className="text-orange-300"/><p className="mt-5 text-xs text-white/45">GATORS</p><p className="mt-1 font-bold">Next game in 17 days</p></div></div></div></main> }
